<?php

namespace app\controllers;

use app\models\Groupe;
use app\models\Student;
use app\models\GenerateSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GenerateController implements the CRUD actions for Student model.
 */
class GenerateController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    public function actionGenerateCalendar()
    {

        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionGenerateGroupe()
    {
        $students = Student::find()->where(['groupe_id' => null])->orderBy(['ball' => SORT_DESC])->all();

        $groupeStudnts = array();
        $groupes = array();
        foreach ($students as $student) {
            $groupeStudnts[$student->speciality->id][] = ['student_id' => $student->id, 'ball' => $student->ball, 'kode' => $student->speciality->codeword . '-' . date('Y')];
            $groupes[$student->speciality->id] = $student->speciality->codeword . '-' . date('Y');
        }

        foreach ($groupes as $groupe) {
            $newGroupe = new Groupe();
            $newGroupe->name = $groupe;
            $newGroupe->save();
        }

        $groupe = Groupe::find()->all();

        foreach ($groupeStudnts as $groupeStudnt) {
            foreach ($groupeStudnt as $std) {
                $item = Student::find()->where(['id' => $std['student_id']])->one();
                foreach ($groupe as $value) {
                    if ($value->name == $std['kode']) {
                        $item->groupe_id = $value->id;
                    }
                }
                $item->save();
            }
        }

        return json_encode($groupes);
    }

    /**
     * Lists all Student models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new GenerateSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Student model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Student model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Student();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Student model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Student model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Student model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Student the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Student::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
